### ISSUE TITLE
Search bar not allowing text / not showing it.

### ISSUE THREAD

**Issue by Mr-Conos** [clickette/main#6]
Hey there! When I try typing into the text bar, it seems to not allow text. 

Example below --
https://user-images.githubusercontent.com/76495776/193483525-498a63aa-2d13-4844-b1ba-6a59e763679e.mov

I am using chrome version 105.0.5195.125 on macOS.

**Comment by ClaytonTDM** [comment]
Hmm, I can't replicate that issue. Probably just an issue with your device.

**Comment by ClaytonTDM** [comment]
Weird, it only happens on apple devices.

**Comment by ClaytonTDM** [comment]
Might be a font issue. Can you try again?
(commit [2702e8e](https://github.com/clickette/main/commit/2702e8e0f2a31e6aa0fbe3fb3596c25b80821cdd))
